"""GrowMap v0.3 — FETCH ALL 10K Perenual plants
Uses per_page=100 for minimal requests. Auto-saves & resumes.

Run: python fetch_all.py YOUR_API_KEY
"""

import json, sys, time, urllib.request, urllib.error, os

API_KEY = sys.argv[1] if len(sys.argv) > 1 else ''
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT = os.path.join(SCRIPT_DIR, 'data', 'plants-perenual.js')
PROGRESS_FILE = os.path.join(SCRIPT_DIR, 'data', 'fetch_progress.json')

def fetch_page(page, per_page=100):
    url = f'https://perenual.com/api/species-list?key={API_KEY}&page={page}&per_page={per_page}'
    try:
        req = urllib.request.Request(url)
        with urllib.request.urlopen(req, timeout=30) as resp:
            return json.loads(resp.read().decode()), None
    except urllib.error.HTTPError as e:
        return None, str(e.code) if e.code == 429 else str(e)
    except Exception as e:
        return None, str(e)

def normalize(p):
    sci = p.get('scientific_name', '')
    if isinstance(sci, list):
        sci = sci[0] if sci else ''
    common = p.get('common_name', '') or ''
    if not common and not sci:
        return None
    
    img = p.get('default_image', {}) or {}
    image_url = img.get('original_url') or img.get('regular_url') or img.get('medium_url')
    thumbnail = img.get('thumbnail') or img.get('small_url') or image_url
    
    sunlight = p.get('sunlight') or []
    if isinstance(sunlight, list):
        full = any(s and 'full sun' in s.lower() for s in sunlight)
        part = any(s and 'part' in s.lower() for s in sunlight)
        shade = any(s and 'shade' in s.lower() for s in sunlight)
    else:
        full = part = shade = False
    sun_hours = 8 if full else (5 if part else (3 if shade else 6))
    
    min_f = p.get('temperature_min_F')
    max_f = p.get('temperature_max_F')
    temp_min = round((min_f - 32) * 5 / 9) if min_f else None
    temp_max = round((max_f - 32) * 5 / 9) if max_f else None
    
    ph_min = float(p['ph_min']) if p.get('ph_min') is not None else None
    ph_max = float(p['ph_max']) if p.get('ph_max') is not None else None
    hardiness = p.get('hardiness') or {}
    
    description = p.get('description', '') or ''
    if not description:
        description = f'{common} ({sci}) — a species from Perenual plant database.'
    
    return {
        'id': f'perenual:{p["id"]}',
        'source': 'perenual',
        'name': common,
        'scientificName': sci,
        'category': 'flower', 'emoji': '🌱',
        'description': description,
        'imageUrl': image_url,
        'thumbnailUrl': thumbnail,
        'edible': p.get('edible') in [True, 'true', 1, '1'],
        'cycle': p.get('cycle') or 'Perennial',
        'requirements': {
            'tempMin': temp_min, 'tempMax': temp_max,
            'tempOptimalMin': temp_min + 3 if temp_min else None,
            'tempOptimalMax': temp_max - 3 if temp_max else None,
            'annualRainfallMin': 300, 'annualRainfallMax': 1200,
            'humidityMin': None, 'humidityMax': None,
            'soilPhMin': ph_min, 'soilPhMax': ph_max,
            'sunlightHoursMin': sun_hours,
            'frostTolerant': None, 'droughtTolerant': False,
            'hardinessZoneMin': hardiness.get('min'),
            'hardinessZoneMax': hardiness.get('max'),
        },
        'growingSeason': p.get('cycle') or 'Perennial',
        'funFact': '',
    }

def save(all_plants, last_page, total_pages):
    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    # Save JS
    with open(OUTPUT, 'w', encoding='utf-8') as f:
        f.write(f'// Auto-generated by fetch_all.py — {len(all_plants)} plants\n')
        f.write('const PLANTS_PERENUAL = ')
        json.dump(all_plants, f, indent=2, ensure_ascii=False)
        f.write(';\n')
    # Save progress
    with open(PROGRESS_FILE, 'w') as f:
        json.dump({'last_page': last_page, 'total_pages': total_pages}, f)
    print(f"  💾 Saved: {len(all_plants)} plants (page {last_page}/{total_pages}) [{os.path.getsize(OUTPUT)//1024}KB]")

def main():
    prog = {'last_page': 0, 'total_pages': 337}
    if os.path.exists(PROGRESS_FILE):
        with open(PROGRESS_FILE) as f:
            prog = json.load(f)
    
    start_page = prog['last_page'] + 1
    total_pages = prog['total_pages']
    
    # Load existing plants if any
    all_plants = []
    if os.path.exists(OUTPUT) and start_page > 1:
        # Re-read from existing file
        with open(OUTPUT, encoding='utf-8') as f:
            content = f.read()
        import re
        match = re.search(r'const PLANTS_PERENUAL = (\[.*?\]);', content, re.DOTALL)
        if match:
            all_plants = json.loads(match.group(1))
    
    print(f"🌱 Fetching ALL Perenual pages (per_page=100)")
    print(f"   Resume from page {start_page}/{total_pages}")
    print(f"   Already have {len(all_plants)} plants\n")
    
    page = start_page
    backoff = 1.5
    
    while page <= total_pages:
        print(f"  📄 Page {page}/{total_pages}...", end=' ')
        data, err = fetch_page(page)
        
        if err == '429':
            print(f"⚠️ 429! Waiting {backoff:.0f}s...")
            time.sleep(backoff)
            backoff = min(backoff * 2, 120)
            continue
        
        if err:
            print(f"⚠️ {err}")
            backoff = min(backoff * 2, 60)
            time.sleep(5)
            continue
        
        backoff = 1.5  # reset on success
        plants = data.get('data', [])
        
        if not plants:
            print("⏹ No more plants")
            break
        
        if data.get('last_page'):
            total_pages = data['last_page']
        
        count = 0
        for p in plants:
            plant = normalize(p)
            if plant:
                all_plants.append(plant)
                count += 1
        
        print(f"✓ {count} plants (total: {len(all_plants)})")
        save(all_plants, page, total_pages)
        
        page += 1
        time.sleep(0.5)  # mild rate limiting
    
    print(f"\n{'='*50}")
    print(f"✅ DONE! {len(all_plants)} plants from {page-1} pages")
    print(f"📝 Saved to: {OUTPUT}")

if __name__ == '__main__':
    if not API_KEY:
        print("Usage: python fetch_all.py YOUR_PERENUAL_API_KEY")
        sys.exit(1)
    main()
