"""GrowMap v0.3 — Pre-fetch Perenual plants into JS file"""
import json, sys, time, urllib.request, urllib.error, os, traceback

API_KEY = sys.argv[1] if len(sys.argv) > 1 else ''
PAGES = 80
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT = os.path.join(SCRIPT_DIR, 'data', 'plants-perenual.js')

def main():
    print(f"🌱 Fetching {PAGES} pages from Perenual API...")
    all_plants = []
    
    for page in range(1, PAGES + 1):
        url = f'https://perenual.com/api/species-list?key={API_KEY}&page={page}'
        print(f"  📄 Page {page}/{PAGES}...", end=' ')
        try:
            req = urllib.request.Request(url)
            with urllib.request.urlopen(req, timeout=15) as resp:
                data = json.loads(resp.read().decode())
        except Exception as e:
            print(f"⚠️ {e}")
            break
        
        plants = data.get('data', [])
        if not plants:
            print("⏹ No more plants")
            break
        
        count = 0
        for p in plants:
            sci = p.get('scientific_name', '')
            if isinstance(sci, list):
                sci = sci[0] if sci else ''
            common = p.get('common_name', '') or ''
            if not common and not sci:
                continue
            
            img = p.get('default_image', {}) or {}
            image_url = img.get('original_url') or img.get('regular_url') or img.get('medium_url')
            thumbnail = img.get('thumbnail') or img.get('small_url') or image_url
            
            sunlight = p.get('sunlight') or []
            if isinstance(sunlight, list):
                full = any(s and 'full sun' in s.lower() for s in sunlight)
                part = any(s and 'part' in s.lower() for s in sunlight)
                shade = any(s and 'shade' in s.lower() for s in sunlight)
            else:
                full = part = shade = False
            sun_hours = 8 if full else (5 if part else (3 if shade else 6))
            
            min_f = p.get('temperature_min_F')
            max_f = p.get('temperature_max_F')
            temp_min = round((min_f - 32) * 5 / 9) if min_f else None
            temp_max = round((max_f - 32) * 5 / 9) if max_f else None
            
            ph_min = float(p['ph_min']) if p.get('ph_min') is not None else None
            ph_max = float(p['ph_max']) if p.get('ph_max') is not None else None
            
            hardiness = p.get('hardiness') or {}
            
            description = p.get('description', '') or ''
            if not description:
                description = f'{common} ({sci}) — a species from the Perenual plant database with real growing requirements and images.'
            
            plant = {
                'id': f'perenual:{p["id"]}',
                'source': 'perenual',
                'name': common,
                'scientificName': sci,
                'category': 'flower',
                'emoji': '🌱',
                'description': description,
                'imageUrl': image_url,
                'thumbnailUrl': thumbnail,
                'edible': p.get('edible') in [True, 'true', 1, '1'],
                'cycle': p.get('cycle') or 'Perennial',
                'requirements': {
                    'tempMin': temp_min,
                    'tempMax': temp_max,
                    'tempOptimalMin': temp_min + 3 if temp_min else None,
                    'tempOptimalMax': temp_max - 3 if temp_max else None,
                    'annualRainfallMin': 300,
                    'annualRainfallMax': 1200,
                    'humidityMin': None,
                    'humidityMax': None,
                    'soilPhMin': ph_min,
                    'soilPhMax': ph_max,
                    'sunlightHoursMin': sun_hours,
                    'frostTolerant': None,
                    'droughtTolerant': False,
                    'hardinessZoneMin': hardiness.get('min'),
                    'hardinessZoneMax': hardiness.get('max'),
                },
                'growingSeason': p.get('cycle') or 'Perennial',
                'funFact': '',
            }
            all_plants.append(plant)
            count += 1
        
        print(f"✓ {count} plants")
        time.sleep(0.3)
    
    print(f"\n✅ Total: {len(all_plants)} plants")
    
    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    with open(OUTPUT, 'w', encoding='utf-8') as f:
        f.write('// Auto-generated by fetch.py\n')
        f.write(f'// {len(all_plants)} plants from Perenual API\n')
        f.write('const PLANTS_PERENUAL = ')
        json.dump(all_plants, f, indent=2, ensure_ascii=False)
        f.write(';\n')
    
    print(f"📝 Written: {OUTPUT}")
    print(f"🚀 Done!")

if __name__ == '__main__':
    main()
